FROM ubuntu
MAINTAINER Michael Bartling "michael.bartling15@gmail.com"

RUN apt-get update
RUN apt-get install -y \
    git \
    python3 \
    python3-pip \
    gcc \
    wget \
    lcov \
    g++ 
RUN pip3 install --upgrade pip setuptools wheel
COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN pip3 install pytest graphviz

