FROM ubuntu
MAINTAINER Michael Bartling "michael.bartling15@gmail.com"

RUN apt-get update
RUN apt-get install -y \
    git \
    python3 \
    python3-pip \
    gcc \
    wget \
    lcov \
    g++ 
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install pytest graphviz
COPY . .
RUN python3 setup.py install

