# -*- coding:utf8 -*-
import os
from tempfile import NamedTemporaryFile

import idx2numpy as idx2np
import numpy as np
import tensorflow as tf
from tensorflow.core.framework.graph_pb2 import GraphDef
from tensorflow.tools.graph_transforms import TransformGraph

from .operators import OperatorFactory
from .transformer.pipline import TransformerPipeline
from .ir import uTensorGraph
from .snippets import (CommentSnippet, ContextHeaderSnippet,
                       ContextSnippetsContainer, CreateTensorIdxSnippet)
from .snippets.composer import Composer

__all__ = ["CodeGenerator"]


class CodeGenerator(object):
  def __init__(self, model_file,
               idx_dir,
               embed_data_dir,
               trans_methods,
               output_nodes,
               debug_cmt=False,
               **trans_kwargs):
    self.model_file = model_file
    if not os.path.exists(idx_dir):
      os.makedirs(idx_dir)
    self.idx_dir = idx_dir
    self.embed_data_dir = embed_data_dir.rstrip("/")
    self.trans_methods = trans_methods
    self.output_nodes = output_nodes
    self.debug_cmt = debug_cmt
    self.trans_kwargs = trans_kwargs

  def generate(self, src_fname):
    _, ext = os.path.splitext(self.model_file)
    if ext == '.pb':
      self._generate_from_pb(src_fname)
    else:
      raise ValueError('Support only pb file')

  def _generate_from_pb(self, src_fname):
    """Generate source and header files
    """
    fname, _ = os.path.splitext(src_fname)
    graph_name, _ = os.path.splitext(os.path.basename(self.model_file))
    guard_name = fname.replace('/', '_')
    header_snippet = ContextHeaderSnippet(guard_name, graph_name)

    composer = Composer()
    header_fname = '{}.hpp'.format(fname)
    header_name = os.path.basename(header_fname)
    container = ContextSnippetsContainer(graph_name, header_name)

    opFactory = OperatorFactory()

    graph_def = tf.GraphDef()
    with tf.gfile.FastGFile(self.model_file, 'rb') as fid:
      graph_def.ParseFromString(fid.read())
    ugraph = uTensorGraph(graph_def, self.output_nodes)
    print("Transforming graph: {}".format(self.model_file))
    quant_ugraph = self._transform_graph(ugraph,
                                         self.trans_methods,
                                         self.trans_kwargs)
    print('Graph transormation done')

    for op_id, op_name in enumerate(quant_ugraph.topo_order):
      op_info = quant_ugraph.ops_info[op_name]
      op_type = op_info.op_type
      if op_type == "Placeholder":
        out_tname = op_info.output_tensors[0].name
        ref_count = 0 #ref_counts[0]
        container.template_vars["placeholders"].append(out_tname)
        container.template_vars["ref_counts"].append(ref_count)
        header_snippet.template_vars["placeholders"].append(out_tname)
      elif op_type == 'Const':
        out_tname, out_dtype, _ = op_info.output_tensors[0]
        ref_count = 0 #ref_counts[0]
        pre_tname = self._tf_prepare_tensor_name(out_tname)
        idx_fname = "{}.idx".format(pre_tname)
        snippet = CreateTensorIdxSnippet(self.embed_data_dir, out_tname,
                                         idx_fname=idx_fname,
                                         np_dtype=out_dtype,
                                         ref_count=ref_count)
        container.add_snippet(snippet)
        idx_path = os.path.join(self.idx_dir, idx_fname)
        value = op_info.op_attr['value'].value
        self._tf_save_data(idx_path, value)
      else:
        snippet = opFactory.createOperatorSnippet(op_info)
        container.add_snippet(snippet)

      if self.debug_cmt:
        comments = ["<<< Operation id {}: {}".format(op_id, op_name),
                    ">>> Operation id {}: {}".format(op_id + 1, op_name)]
        cmt_snippet = CommentSnippet(comments)
        container.add_snippet(cmt_snippet)
    composer.add_snippet(container)

    print("Generate header file: {}".format(header_fname))
    with open(header_fname, "w") as wf:
      wf.write('// Auto generated by utensor-cli\n\n')
      wf.write(header_snippet.render())
    print("Generate source file: {}".format(src_fname))
    with open(src_fname, "w") as wf:
      wf.write('// Auto generated by utensor-cli\n\n')
      wf.write(composer.compose())

  def _transform_graph(self, ugraph, methods, trans_kwargs):
    pipeline = TransformerPipeline(methods, trans_kwargs)
    return pipeline.transform(ugraph)

  def _tf_load_graph_def(self, pb_fname):
    with tf.gfile.FastGFile(pb_fname, 'rb') as fid:
      graph_def = tf.GraphDef()
      graph_def.ParseFromString(fid.read())
    return graph_def

  def _tf_prepare_tensor_name(self, tensor_name):
    """Replace all ':' and '/' with '_' in a given tensor name
    """
    prepared = tensor_name.replace(":", "_").replace("/", "_")
    return prepared

  def _tf_save_data(self, path, value):
    np_array = value.np_array
    if np_array.shape == ():
      np_array = np.array([np_array])
    with open(path, "wb") as fid:
      idx2np.convert_to_file(fid, np_array)
    print("saving {}".format(path))
